<?php
/**
 * Shortcodes for the MU HR Comp plugin
 *
 * @package MU HR Comp
 */

/**
 * Shortcode to display the Position Starting Letter list
 *
 * @return string
 */
function mu_hrcomp_letters_shortcode() {

	if ( get_transient( 'mu_hrcomp_letters' ) ) {
		$letters = get_transient( 'mu_hrcomp_letters' );
	} else {
		global $wpdb;

		$letters = $wpdb->get_results( 'SELECT DISTINCT LEFT(post_title, 1) as letter FROM ' . $wpdb->get_blog_prefix() . 'posts WHERE post_type = "mu-position" ORDER BY letter;' );

		set_transient( 'mu_hrcomp_letters', $letters, 60 * 60 * 24 );
	}

	$html = '<div class="flex flex-wrap space-x-1 justify-center">';
	foreach ( $letters as $letter ) {
		$html .= '<a href="?alpha=' . $letter->letter . '" class="text-base lg:text-lg mb-2 py-2 px-3 bg-gray-100 text-gray-700 hover:bg-white hover:text-gray-800 no-underline hover:underline">' . $letter->letter . '</a>';
	}
	$html .= '</div>';

	wp_reset_postdata();

	return $html;

}
add_shortcode( 'mu_hrcomp_letters', 'mu_hrcomp_letters_shortcode' );

/**
 * Shortcode to display listing of Positions.
 *
 * @return string Shortcode output.
 */
function mu_hrcomp_shortcode() {
	if ( get_query_var( 'alpha' ) ) {
		$alpha_letter = esc_attr( get_query_var( 'alpha' ) );
	} else {
		$alpha_letter = 'A';
	}

	$args = array(
		'post_type'      => 'mu-position',
		'posts_per_page' => -1,
		'orderby'        => array(
			'title' => 'ASC',
		),
		'extend_where'   => "(post_title like '" . $alpha_letter . "%')",
	);

	$alpha_query = new WP_Query( $args );

	$html  = '<table class="table w-full table-striped table-bordered table-services">';
	$html .= '<thead>';
	$html .= '<tr>';
	$html .= '<th>Current Title</th>';
	$html .= '<th class="w-1/6 text-center">New Pay Grade</th>';
	$html .= '<th class="w-1/6 text-center">Salary Range Min</th>';
	$html .= '<th class="w-1/6 text-center">Salary Range Mid</th>';
	$html .= '<th class="w-1/6 text-center">Salary Range Max</th>';
	$html .= '</tr>';
	$html .= '</thead>';
	$html .= '<tbody>';

	if ( $alpha_query->have_posts() ) {
		while ( $alpha_query->have_posts() ) {
			$alpha_query->the_post();
			$html .= '<tr>';

			if ( get_field( 'position_upload_pdf', get_the_id() ) ) {
				$html .= '<td><a href="' . esc_url( get_field( 'position_upload_pdf' )['url'], get_the_id() ) . '">' . get_the_title() . '</a></td>';
			} elseif ( get_field( 'position_url_pdf', get_the_id() ) ) {
				$html .= '<td><a href="' . esc_url( get_field( 'position_url_pdf' ), get_the_id() ) . '">' . get_the_title() . '</a></td>';
			} else {
				$html .= '<td>' . get_the_title() . '</td>';
			}

			$html .= '<td>' . get_field( 'position_new_pay_grade', get_the_id() ) . '</td>';
			$html .= '<td>' . get_field( 'position_salary_min', get_the_id() ) . '</td>';
			$html .= '<td>' . get_field( 'position_salary_mid', get_the_id() ) . '</td>';
			$html .= '<td>' . get_field( 'position_salary_max', get_the_id() ) . '</td>';
			$html .= '';
		}
	} else {
		$html .= '<tr>';
		$html .= '<td colspan="5">No positions start with the letter ' . esc_attr( $alpha_letter ) . '.</td>';
		$html .= '</tr>';
	}

	$html .= '</tbody>';
	$html .= '</table>';

	wp_reset_postdata();

	return $html;
}
add_shortcode( 'mu_hr_compensation', 'mu_hrcomp_shortcode' );

function mu_hrcomp_initial_data() {

	$positions = array(
		array(
			"title" => "Academic Advisor",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/1.pdf",
			"pay_grade" => "4",
			"salary_min" => "$35,568",
			"salary_mid" => "$38,400",
			"salary_max" => "$47,300",
		),
		array(
			"title" => "Academic Laboratory Instruction Assistant",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/2.pdf",
			"pay_grade" => "5",
			"salary_min" => "$34,200",
			"salary_mid" => "$44,400",
			"salary_max" => "$54,600",
		),
		array(
			"title" => "Academic Laboratory Manager II",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/4.pdf",
			"pay_grade" => "5",
			"salary_min" => "$35,568",
			"salary_mid" => "$44,400",
			"salary_max" => "$54,600",
		),
		array(
			"title" => "Academic Laboratory Manager III",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/5.pdf",
			"pay_grade" => "6",
			"salary_min" => "$39,500",
			"salary_mid" => "$51,400",
			"salary_max" => "$63,300",
		),
		array(
			"title" => "Academic Program Associate",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/189.pdf",
			"pay_grade" => "3",
			"salary_min" => "$25,600",
			"salary_mid" => "$33,300",
			"salary_max" => "$41,000",
		),
		array(
			"title" => "Accountant",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/6.pdf",
			"pay_grade" => "5",
			"salary_min" => "$34,200",
			"salary_mid" => "$44,400",
			"salary_max" => "$54,600",
		),
		array(
			"title" => "Accountant Senior",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/7.pdf",
			"pay_grade" => "6",
			"salary_min" => "$39,500",
			"salary_mid" => "$51,400",
			"salary_max" => "$63,300",
		),
		array(
			"title" => "Administrative Applications Software Specialist",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/10.pdf",
			"pay_grade" => "6",
			"salary_min" => "$39,500",
			"salary_mid" => "$51,400",
			"salary_max" => "$63,300",
		),
		array(
			"title" => "Administrative Applications Software Specialist Senior",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/11.pdf",
			"pay_grade" => "7",
			"salary_min" => "$45,700",
			"salary_mid" => "$59,400",
			"salary_max" => "$73,100",
		),
		array(
			"title" => "Administrative Assistant",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/12.pdf",
			"pay_grade" => "3",
			"salary_min" => "$25,600",
			"salary_mid" => "$33,300",
			"salary_max" => "$41,000",
		),
		array(
			"title" => "Administrative Assistant Senior",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/13.pdf",
			"pay_grade" => "4",
			"salary_min" => "$29,500",
			"salary_mid" => "$38,400",
			"salary_max" => "$47,300",
		),
		array(
			"title" => "Administrative Associate",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/14.pdf",
			"pay_grade" => "3",
			"salary_min" => "$25,600",
			"salary_mid" => "$33,300",
			"salary_max" => "$41,000",
		),
		array(
			"title" => "Administrative Secretary",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/15.pdf",
			"pay_grade" => "2",
			"salary_min" => "$22,200",
			"salary_mid" => "$28,800",
			"salary_max" => "$35,400",
		),
		array(
			"title" => "Administrative Secretary Senior",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/16.pdf",
			"pay_grade" => "3",
			"salary_min" => "$25,600",
			"salary_mid" => "$33,300",
			"salary_max" => "$41,000",
		),
		array(
			"title" => "Admissions Assistant 3",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/17.pdf",
			"pay_grade" => "3",
			"salary_min" => "$25,600",
			"salary_mid" => "$33,300",
			"salary_max" => "$41,000",
		),
		array(
			"title" => "Admissions Counselor",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/18.pdf",
			"pay_grade" => "4",
			"salary_min" => "$29,500",
			"salary_mid" => "$38,400",
			"salary_max" => "$47,300",
		),
		array(
			"title" => "Admissions Counselor Senior",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/19.pdf",
			"pay_grade" => "4",
			"salary_min" => "$29,500",
			"salary_mid" => "$38,400",
			"salary_max" => "$47,300",
		),
		array(
			"title" => "Application Systems Analyst Programmer",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/20.pdf",
			"pay_grade" => "6",
			"salary_min" => "$39,500",
			"salary_mid" => "$51,400",
			"salary_max" => "$63,300",
		),
		array(
			"title" => "Application Systems Analyst Programmer Lead",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/21.pdf",
			"pay_grade" => "8",
			"salary_min" => "$52,800",
			"salary_mid" => "$68,600",
			"salary_max" => "$84,400",
		),
		array(
			"title" => "Application Systems Analyst Programmer Senior",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/22.pdf",
			"pay_grade" => "7",
			"salary_min" => "$45,700",
			"salary_mid" => "$59,400",
			"salary_max" => "$73,100",
		),
		array(
			"title" => "Applications Programmer",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/23.pdf",
			"pay_grade" => "4",
			"salary_min" => "$29,500",
			"salary_mid" => "$38,400",
			"salary_max" => "$47,300",
		),
		array(
			"title" => "Apprentice III",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/24.pdf",
			"pay_grade" => "1",
			"salary_min" => "$19,200",
			"salary_mid" => "$24,900",
			"salary_max" => "$30,600",
		),
		array(
			"title" => "Assistant Accountant",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/191.pdf",
			"pay_grade" => "3",
			"salary_min" => "$25,600",
			"salary_mid" => "$33,300",
			"salary_max" => "$41,000",
		),
		array(
			"title" => "Assistant Director Physical Plant",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/25.pdf",
			"pay_grade" => "6",
			"salary_min" => "$39,500",
			"salary_mid" => "$51,400",
			"salary_max" => "$63,300",
		),
		array(
			"title" => "Assistant Director Physical Plant I",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/26.pdf",
			"pay_grade" => "6",
			"salary_min" => "$39,500",
			"salary_mid" => "$51,400",
			"salary_max" => "$63,300",
		),
		array(
			"title" => "Assistant Director Physical Plant II",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/27.pdf",
			"pay_grade" => "6",
			"salary_min" => "$39,500",
			"salary_mid" => "$51,400",
			"salary_max" => "$63,300",
		),
		array(
			"title" => "Assistant Director Purchasing",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/28.pdf",
			"pay_grade" => "7",
			"salary_min" => "$45,700",
			"salary_mid" => "$59,400",
			"salary_max" => "$73,100",
		),
		array(
			"title" => "Assistant Manager College Center",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/29.pdf",
			"pay_grade" => "2",
			"salary_min" => "$22,200",
			"salary_mid" => "$28,800",
			"salary_max" => "$35,400",
		),
		array(
			"title" => "Assistant Supervisor Campus Services",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/30.pdf",
			"pay_grade" => "3",
			"salary_min" => "$25,600",
			"salary_mid" => "$33,300",
			"salary_max" => "$41,000",
		),
		array(
			"title" => "Assistant Supervisor Printing",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/31.pdf",
			"pay_grade" => "3",
			"salary_min" => "$25,600",
			"salary_mid" => "$33,300",
			"salary_max" => "$41,000",
		),
		array(
			"title" => "Associate Sports Information Director",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/32.pdf",
			"pay_grade" => "3",
			"salary_min" => "$35,568",
			"salary_mid" => "$33,300",
			"salary_max" => "$41,000",
		),
		array(
			"title" => "Athletic Equipment Coordinator",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/33.pdf",
			"pay_grade" => "1",
			"salary_min" => "$19,200",
			"salary_mid" => "$24,900",
			"salary_max" => "$30,600",
		),
		array(
			"title" => "Athletic Equipment Manager",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/34.pdf",
			"pay_grade" => "2",
			"salary_min" => "$22,200",
			"salary_mid" => "$28,800",
			"salary_max" => "$35,400",
		),
		array(
			"title" => "Athletic Facilities Manager",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/35.pdf",
			"pay_grade" => "5",
			"salary_min" => "$35,568",
			"salary_mid" => "$44,400",
			"salary_max" => "$54,600",
		),
		array(
			"title" => "Broadcast Engineer",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/36.pdf",
			"pay_grade" => "5",
			"salary_min" => "$35,568",
			"salary_mid" => "$44,400",
			"salary_max" => "$54,600",
		),
		array(
			"title" => "Budget Analyst",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/37.pdf",
			"pay_grade" => "4",
			"salary_min" => "$29,500",
			"salary_mid" => "$38,400",
			"salary_max" => "$47,300",
		),
		array(
			"title" => "Budget Analyst Senior",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/38.pdf",
			"pay_grade" => "5",
			"salary_min" => "$35,568",
			"salary_mid" => "$44,400",
			"salary_max" => "$54,600",
		),
		array(
			"title" => "Business Clerk",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/39.pdf",
			"pay_grade" => "2",
			"salary_min" => "$22,200",
			"salary_mid" => "$28,800",
			"salary_max" => "$35,400",
		),
		array(
			"title" => "Business Manager I",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/40.pdf",
			"pay_grade" => "5",
			"salary_min" => "$35,568",
			"salary_mid" => "$44,400",
			"salary_max" => "$54,600",
		),
		array(
			"title" => "Business Manager II",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/41.pdf",
			"pay_grade" => "6",
			"salary_min" => "$39,500",
			"salary_mid" => "$51,400",
			"salary_max" => "$63,300",
		),
		array(
			"title" => "Business Research Analyst",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/42.pdf",
			"pay_grade" => "5",
			"salary_min" => "$35,568",
			"salary_mid" => "$44,400",
			"salary_max" => "$54,600",
		),
		array(
			"title" => "Campus Manager",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/43.pdf",
			"pay_grade" => "5",
			"salary_min" => "$34,200",
			"salary_mid" => "$44,400",
			"salary_max" => "$54,600",
		),
		array(
			"title" => "Campus Police Officer",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/44.pdf",
			"pay_grade" => "4",
			"salary_min" => "$29,500",
			"salary_mid" => "$38,400",
			"salary_max" => "$47,300",
		),
		array(
			"title" => "Campus Police Officer Lead",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/45.pdf",
			"pay_grade" => "6",
			"salary_min" => "$39,500",
			"salary_mid" => "$51,400",
			"salary_max" => "$63,300",
		),
		array(
			"title" => "Campus Police Officer Senior",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/46.pdf",
			"pay_grade" => "5",
			"salary_min" => "$34,200",
			"salary_mid" => "$44,400",
			"salary_max" => "$54,600",
		),
		array(
			"title" => "Campus Police Officer Supervisor",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/47.pdf",
			"pay_grade" => "7",
			"salary_min" => "$45,700",
			"salary_mid" => "$59,400",
			"salary_max" => "$73,100",
		),
		array(
			"title" => "Campus Service Worker",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/48.pdf",
			"pay_grade" => "1",
			"salary_min" => "$19,200",
			"salary_mid" => "$24,900",
			"salary_max" => "$30,600",
		),
		array(
			"title" => "Campus Service Worker Lead",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/49.pdf",
			"pay_grade" => "2",
			"salary_min" => "$22,200",
			"salary_mid" => "$28,800",
			"salary_max" => "$35,400",
		),
		array(
			"title" => "Career Services Technician",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/50.pdf",
			"pay_grade" => "2",
			"salary_min" => "$22,200",
			"salary_mid" => "$28,800",
			"salary_max" => "$35,400",
		),
		array(
			"title" => "Certified Landscape Worker Lead",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/51.pdf",
			"pay_grade" => "2",
			"salary_min" => "$22,200",
			"salary_mid" => "$28,800",
			"salary_max" => "$35,400",
		),
		array(
			"title" => "Certified Supervisor Grounds",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/52.pdf",
			"pay_grade" => "4",
			"salary_min" => "$29,500",
			"salary_mid" => "$38,400",
			"salary_max" => "$47,300",
		),
		array(
			"title" => "Communications Operator",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/53.pdf",
			"pay_grade" => "1",
			"salary_min" => "$19,200",
			"salary_mid" => "$24,900",
			"salary_max" => "$30,600",
		),
		array(
			"title" => "Construction Project Manager Senior",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/54.pdf",
			"pay_grade" => "5",
			"salary_min" => "$35,568",
			"salary_mid" => "$44,400",
			"salary_max" => "$54,600",
		),
		array(
			"title" => "Contract Specialist",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/55.pdf",
			"pay_grade" => "5",
			"salary_min" => "$35,568",
			"salary_mid" => "$44,400",
			"salary_max" => "$54,600",
		),
		array(
			"title" => "Coordinator Campus Learning Centers",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/56.pdf",
			"pay_grade" => "5",
			"salary_min" => "$35,568",
			"salary_mid" => "$44,400",
			"salary_max" => "$54,600",
		),
		array(
			"title" => "Counselor I",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/57.pdf",
			"pay_grade" => "4",
			"salary_min" => "$29,500",
			"salary_mid" => "$38,400",
			"salary_max" => "$47,300",
		),
		array(
			"title" => "Counselor II",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/58.pdf",
			"pay_grade" => "4",
			"salary_min" => "$29,500",
			"salary_mid" => "$38,400",
			"salary_max" => "$47,300",
		),
		array(
			"title" => "Data Network Specialist I",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/59.pdf",
			"pay_grade" => "4",
			"salary_min" => "$29,500",
			"salary_mid" => "$38,400",
			"salary_max" => "$47,300",
		),
		array(
			"title" => "Data Technician I",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/60.pdf",
			"pay_grade" => "3",
			"salary_min" => "$25,600",
			"salary_mid" => "$33,300",
			"salary_max" => "$41,000",
		),
		array(
			"title" => "Data Technician II",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/61.pdf",
			"pay_grade" => "3",
			"salary_min" => "$25,600",
			"salary_mid" => "$33,300",
			"salary_max" => "$41,000",
		),
		array(
			"title" => "Database Specialist",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/62.pdf",
			"pay_grade" => "6",
			"salary_min" => "$39,500",
			"salary_mid" => "$51,400",
			"salary_max" => "$63,300",
		),
		array(
			"title" => "Database Technician I",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/63.pdf",
			"pay_grade" => "3",
			"salary_min" => "$25,600",
			"salary_mid" => "$33,300",
			"salary_max" => "$41,000",
		),
		array(
			"title" => "Database Technician II",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/64.pdf",
			"pay_grade" => "3",
			"salary_min" => "$25,600",
			"salary_mid" => "$33,300",
			"salary_max" => "$41,000",
		),
		array(
			"title" => "Director Off Campus Center",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/65.pdf",
			"pay_grade" => "7",
			"salary_min" => "$45,700",
			"salary_mid" => "$59,400",
			"salary_max" => "$73,100",
		),
		array(
			"title" => "Director Physical Plant I",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/66.pdf",
			"pay_grade" => "6",
			"salary_min" => "$39,500",
			"salary_mid" => "$51,400",
			"salary_max" => "$63,300",
		),
		array(
			"title" => "Director Student Services",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/67.pdf",
			"pay_grade" => "6",
			"salary_min" => "$39,500",
			"salary_mid" => "$51,400",
			"salary_max" => "$63,300",
		),
		array(
			"title" => "Director Theatre Facilities",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/69.pdf",
			"pay_grade" => "6",
			"salary_min" => "$39,500",
			"salary_mid" => "$51,400",
			"salary_max" => "$63,300",
		),
		array(
			"title" => "Education Credentials Specialist",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/70.pdf",
			"pay_grade" => "5",
			"salary_min" => "$35,568",
			"salary_mid" => "$44,400",
			"salary_max" => "$54,600",
		),
		array(
			"title" => "Electronic Media Technician Senior",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/71.pdf",
			"pay_grade" => "4",
			"salary_min" => "$29,500",
			"salary_mid" => "$38,400",
			"salary_max" => "$47,300",
		),
		array(
			"title" => "Electronics Engineer",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/72.pdf",
			"pay_grade" => "5",
			"salary_min" => "$34,200",
			"salary_mid" => "$44,400",
			"salary_max" => "$54,600",
		),
		array(
			"title" => "Executive Administrative Assistant",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/73.pdf",
			"pay_grade" => "5",
			"salary_min" => "$35,568",
			"salary_mid" => "$44,400",
			"salary_max" => "$54,600",
		),
		array(
			"title" => "Executive Secretary",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/74.pdf",
			"pay_grade" => "4",
			"salary_min" => "$29,500",
			"salary_mid" => "$38,400",
			"salary_max" => "$47,300",
		),
		array(
			"title" => "Financial Aid Assistant III",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/75.pdf",
			"pay_grade" => "2",
			"salary_min" => "$22,200",
			"salary_mid" => "$28,800",
			"salary_max" => "$35,400",
		),
		array(
			"title" => "Financial Aid Counselor",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/76.pdf",
			"pay_grade" => "4",
			"salary_min" => "$29,500",
			"salary_mid" => "$38,400",
			"salary_max" => "$47,300",
		),
		array(
			"title" => "Financial Aid Counselor Senior",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/77.pdf",
			"pay_grade" => "5",
			"salary_min" => "$35,568",
			"salary_mid" => "$44,400",
			"salary_max" => "$54,600",
		),
		array(
			"title" => "Grant Resources Associate",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/78.pdf",
			"pay_grade" => "4",
			"salary_min" => "$29,500",
			"salary_mid" => "$38,400",
			"salary_max" => "$47,300",
		),
		array(
			"title" => "Graphic Arts Designer",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/79.pdf",
			"pay_grade" => "3",
			"salary_min" => "$25,600",
			"salary_mid" => "$33,300",
			"salary_max" => "$41,000",
		),
		array(
			"title" => "Graphic Arts Designer Senior",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/80.pdf",
			"pay_grade" => "4",
			"salary_min" => "$29,500",
			"salary_mid" => "$38,400",
			"salary_max" => "$47,300",
		),
		array(
			"title" => "Human Resources Assistant III",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/81.pdf",
			"pay_grade" => "4",
			"salary_min" => "$29,500",
			"salary_mid" => "$38,400",
			"salary_max" => "$47,300",
		),
		array(
			"title" => "Human Resources Representative",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/82.pdf",
			"pay_grade" => "5",
			"salary_min" => "$35,568",
			"salary_mid" => "$44,400",
			"salary_max" => "$54,600",
		),
		array(
			"title" => "Human Resources Representative Senior",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/83.pdf",
			"pay_grade" => "6",
			"salary_min" => "$39,500",
			"salary_mid" => "$51,400",
			"salary_max" => "$63,300",
		),
		array(
			"title" => "Information Assistant Senior",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/84.pdf",
			"pay_grade" => "3",
			"salary_min" => "$25,600",
			"salary_mid" => "$33,300",
			"salary_max" => "$41,000",
		),
		array(
			"title" => "Information Systems Manager",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/85.pdf",
			"pay_grade" => "7",
			"salary_min" => "$45,700",
			"salary_mid" => "$59,400",
			"salary_max" => "$73,100",
		),
		array(
			"title" => "Information Systems Specialist",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/86.pdf",
			"pay_grade" => "5",
			"salary_min" => "$35,568",
			"salary_mid" => "$44,400",
			"salary_max" => "$54,600",
		),
		array(
			"title" => "Information Systems Technician",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/87.pdf",
			"pay_grade" => "4",
			"salary_min" => "$29,500",
			"salary_mid" => "$38,400",
			"salary_max" => "$47,300",
		),
		array(
			"title" => "Information Technology Consultant",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/88.pdf",
			"pay_grade" => "4",
			"salary_min" => "$29,500",
			"salary_mid" => "$38,400",
			"salary_max" => "$47,300",
		),
		array(
			"title" => "Information Technology Consultant Senior",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/89.pdf",
			"pay_grade" => "5",
			"salary_min" => "$35,568",
			"salary_mid" => "$44,400",
			"salary_max" => "$54,600",
		),
		array(
			"title" => "Institutional Research Analyst Senior",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/90.pdf",
			"pay_grade" => "5",
			"salary_min" => "$35,568",
			"salary_mid" => "$44,400",
			"salary_max" => "$54,600",
		),
		array(
			"title" => "Laboratory Animal Technician I",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/91.pdf",
			"pay_grade" => "2",
			"salary_min" => "$22,200",
			"salary_mid" => "$28,800",
			"salary_max" => "$35,400",
		),
		array(
			"title" => "Laboratory Instrumentation Specialist Senior",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/92.pdf",
			"pay_grade" => "5",
			"salary_min" => "$34,200",
			"salary_mid" => "$44,400",
			"salary_max" => "$54,600",
		),
		array(
			"title" => "Landscape Worker",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/93.pdf",
			"pay_grade" => "1",
			"salary_min" => "$19,200",
			"salary_mid" => "$24,900",
			"salary_max" => "$30,600",
		),
		array(
			"title" => "Landscape Worker Lead",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/94.pdf",
			"pay_grade" => "2",
			"salary_min" => "$22,200",
			"salary_mid" => "$28,800",
			"salary_max" => "$35,400",
		),
		array(
			"title" => "Library Assistant",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/95.pdf",
			"pay_grade" => "2",
			"salary_min" => "$22,200",
			"salary_mid" => "$28,800",
			"salary_max" => "$35,400",
		),
		array(
			"title" => "Library Associate",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/96.pdf",
			"pay_grade" => "3",
			"salary_min" => "$25,600",
			"salary_mid" => "$33,300",
			"salary_max" => "$41,000",
		),
		array(
			"title" => "Library Technical Assistant I",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/97.pdf",
			"pay_grade" => "2",
			"salary_min" => "$22,200",
			"salary_mid" => "$28,800",
			"salary_max" => "$35,400",
		),
		array(
			"title" => "Library Technical Assistant II",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/98.pdf",
			"pay_grade" => "2",
			"salary_min" => "$22,200",
			"salary_mid" => "$28,800",
			"salary_max" => "$35,400",
		),
		array(
			"title" => "Maintenance Worker I",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/99.pdf",
			"pay_grade" => "2",
			"salary_min" => "$22,200",
			"salary_mid" => "$28,800",
			"salary_max" => "$35,400",
		),
		array(
			"title" => "Manager Accounting System",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/100.pdf",
			"pay_grade" => "7",
			"salary_min" => "$45,700",
			"salary_mid" => "$59,400",
			"salary_max" => "$73,100",
		),
		array(
			"title" => "Manager Accounts Payable Senior",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/101.pdf",
			"pay_grade" => "5",
			"salary_min" => "$35,568",
			"salary_mid" => "$44,400",
			"salary_max" => "$54,600",
		),
		array(
			"title" => "Manager Alterations Support",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/102.pdf",
			"pay_grade" => "5",
			"salary_min" => "$35,568",
			"salary_mid" => "$51,400",
			"salary_max" => "$63,300",
		),
		array(
			"title" => "Manager Budget",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/103.pdf",
			"pay_grade" => "6",
			"salary_min" => "$39,500",
			"salary_mid" => "$51,400",
			"salary_max" => "$63,300",
		),
		array(
			"title" => "Manager Business Operations",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/104.pdf",
			"pay_grade" => "7",
			"salary_min" => "$45,700",
			"salary_mid" => "$59,400",
			"salary_max" => "$73,100",
		),
		array(
			"title" => "Manager Campus Academic Affairs",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/105.pdf",
			"pay_grade" => "7",
			"salary_min" => "$45,700",
			"salary_mid" => "$59,400",
			"salary_max" => "$73,100",
		),
		array(
			"title" => "Manager Computer Operations",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/106.pdf",
			"pay_grade" => "6",
			"salary_min" => "$39,500",
			"salary_mid" => "$51,400",
			"salary_max" => "$63,300",
		),
		array(
			"title" => "Manager Computer Services",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/107.pdf",
			"pay_grade" => "7",
			"salary_min" => "$45,700",
			"salary_mid" => "$59,400",
			"salary_max" => "$73,100",
		),
		array(
			"title" => "Manager Graphic Services",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/108.pdf",
			"pay_grade" => "6",
			"salary_min" => "$39,500",
			"salary_mid" => "$51,400",
			"salary_max" => "$63,300",
		),
		array(
			"title" => "Manager Human Resources",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/109.pdf",
			"pay_grade" => "7",
			"salary_min" => "$45,700",
			"salary_mid" => "$59,400",
			"salary_max" => "$73,100",
		),
		array(
			"title" => "Manager Information Services",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/110.pdf",
			"pay_grade" => "7",
			"salary_min" => "$45,700",
			"salary_mid" => "$59,400",
			"salary_max" => "$73,100",
		),
		array(
			"title" => "Manager Library Services",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/111.pdf",
			"pay_grade" => "6",
			"salary_min" => "$39,500",
			"salary_mid" => "$51,400",
			"salary_max" => "$63,300",
		),
		array(
			"title" => "Manager Memorial Student Center Conference and Facilities",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/112.pdf",
			"pay_grade" => "6",
			"salary_min" => "$39,500",
			"salary_mid" => "$51,400",
			"salary_max" => "$63,300",
		),
		array(
			"title" => "Manager Payroll Senior",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/113.pdf",
			"pay_grade" => "5",
			"salary_min" => "$35,568",
			"salary_mid" => "$44,400",
			"salary_max" => "$54,600",
		),
		array(
			"title" => "Manager Photographic Services",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/114.pdf",
			"pay_grade" => "5",
			"salary_min" => "$34,200",
			"salary_mid" => "$44,400",
			"salary_max" => "$54,600",
		),
		array(
			"title" => "Manager Physical Plant I",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/115.pdf",
			"pay_grade" => "4",
			"salary_min" => "$29,500",
			"salary_mid" => "$38,400",
			"salary_max" => "$47,300",
		),
		array(
			"title" => "Manager Physical Plant II",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/116.pdf",
			"pay_grade" => "5",
			"salary_min" => "$34,200",
			"salary_mid" => "$44,400",
			"salary_max" => "$54,600",
		),
		array(
			"title" => "Manager Student Accounts",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/117.pdf",
			"pay_grade" => "6",
			"salary_min" => "$39,500",
			"salary_mid" => "$51,400",
			"salary_max" => "$63,300",
		),
		array(
			"title" => "Materials Handler",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/118.pdf",
			"pay_grade" => "1",
			"salary_min" => "$19,200",
			"salary_mid" => "$24,900",
			"salary_max" => "$30,600",
		),
		array(
			"title" => "Mental Health Specialist",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/119.pdf",
			"pay_grade" => "5",
			"salary_min" => "$35,568",
			"salary_mid" => "$44,400",
			"salary_max" => "$54,600",
		),
		array(
			"title" => "Office Administrator",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/120.pdf",
			"pay_grade" => "4",
			"salary_min" => "$29,500",
			"salary_mid" => "$38,400",
			"salary_max" => "$47,300",
		),
		array(
			"title" => "Office Administrator Senior",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/121.pdf",
			"pay_grade" => "5",
			"salary_min" => "$35,568",
			"salary_mid" => "$44,400",
			"salary_max" => "$54,600",
		),
		array(
			"title" => "Operations Coordinator",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/122.pdf",
			"pay_grade" => "4",
			"salary_min" => "$35,568",
			"salary_mid" => "$38,400",
			"salary_max" => "$47,300",
		),
		array(
			"title" => "Operations Manager",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/123.pdf",
			"pay_grade" => "6",
			"salary_min" => "$39,500",
			"salary_mid" => "$51,400",
			"salary_max" => "$63,300",
		),
		array(
			"title" => "Payroll Representative",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/124.pdf",
			"pay_grade" => "3",
			"salary_min" => "$25,600",
			"salary_mid" => "$33,300",
			"salary_max" => "$41,000",
		),
		array(
			"title" => "Payroll Representative Senior",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/125.pdf",
			"pay_grade" => "4",
			"salary_min" => "$29,500",
			"salary_mid" => "$38,400",
			"salary_max" => "$47,300",
		),
		array(
			"title" => "Piano Technician",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/126.pdf",
			"pay_grade" => "4",
			"salary_min" => "$29,500",
			"salary_mid" => "$38,400",
			"salary_max" => "$47,300",
		),
		array(
			"title" => "Postal Worker I",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/127.pdf",
			"pay_grade" => "1",
			"salary_min" => "$19,200",
			"salary_mid" => "$24,900",
			"salary_max" => "$30,600",
		),
		array(
			"title" => "Postal Worker Lead",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/128.pdf",
			"pay_grade" => "2",
			"salary_min" => "$22,200",
			"salary_mid" => "$28,800",
			"salary_max" => "$35,400",
		),
		array(
			"title" => "Press Operator II",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/129.pdf",
			"pay_grade" => "2",
			"salary_min" => "$22,200",
			"salary_mid" => "$28,800",
			"salary_max" => "$35,400",
		),
		array(
			"title" => "Production Assistant",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/130.pdf",
			"pay_grade" => "2",
			"salary_min" => "$22,200",
			"salary_mid" => "$28,800",
			"salary_max" => "$35,400",
		),
		array(
			"title" => "Program Assistant I",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/132.pdf",
			"pay_grade" => "3",
			"salary_min" => "$25,600",
			"salary_mid" => "$33,300",
			"salary_max" => "$41,000",
		),
		array(
			"title" => "Program Assistant II",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/133.pdf",
			"pay_grade" => "3",
			"salary_min" => "$25,600",
			"salary_mid" => "$33,300",
			"salary_max" => "$41,000",
		),
		array(
			"title" => "Program Assistant III",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/134.pdf",
			"pay_grade" => "3",
			"salary_min" => "$25,600",
			"salary_mid" => "$33,300",
			"salary_max" => "$41,000",
		),
		array(
			"title" => "Program Coordinator",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/135.pdf",
			"pay_grade" => "4",
			"salary_min" => "$29,500",
			"salary_mid" => "$38,400",
			"salary_max" => "$47,300",
		),
		array(
			"title" => "Program Coordinator Senior",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/136.pdf",
			"pay_grade" => "7",
			"salary_min" => "$45,700",
			"salary_mid" => "$59,400",
			"salary_max" => "$73,100",
		),
		array(
			"title" => "Program Manager",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/137.pdf",
			"pay_grade" => "6",
			"salary_min" => "$39,500",
			"salary_mid" => "$51,400",
			"salary_max" => "$63,300",
		),
		array(
			"title" => "Program Specialist",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/138.pdf",
			"pay_grade" => "5",
			"salary_min" => "$35,568",
			"salary_mid" => "$44,400",
			"salary_max" => "$54,600",
		),
		array(
			"title" => "Project Coordinator",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/139.pdf",
			"pay_grade" => "4",
			"salary_min" => "$29,500",
			"salary_mid" => "$38,400",
			"salary_max" => "$47,300",
		),
		array(
			"title" => "Project Coordinator Senior",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/140.pdf",
			"pay_grade" => "5",
			"salary_min" => "$35,568",
			"salary_mid" => "$44,400",
			"salary_max" => "$54,600",
		),
		array(
			"title" => "Public Relations Specialist",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/141.pdf",
			"pay_grade" => "5",
			"salary_min" => "$35,568",
			"salary_mid" => "$44,400",
			"salary_max" => "$54,600",
		),
		array(
			"title" => "Public Safety Dispatcher",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/142.pdf",
			"pay_grade" => "2",
			"salary_min" => "$22,200",
			"salary_mid" => "$28,800",
			"salary_max" => "$35,400",
		),
		array(
			"title" => "Purchasing Agent",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/143.pdf",
			"pay_grade" => "5",
			"salary_min" => "$35,568",
			"salary_mid" => "$44,400",
			"salary_max" => "$54,600",
		),
		array(
			"title" => "Purchasing Assistant II",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/144.pdf",
			"pay_grade" => "2",
			"salary_min" => "$22,200",
			"salary_mid" => "$28,800",
			"salary_max" => "$35,400",
		),
		array(
			"title" => "Radiation Safety Specialist",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/145.pdf",
			"pay_grade" => "4",
			"salary_min" => "$29,500",
			"salary_mid" => "$38,400",
			"salary_max" => "$47,300",
		),
		array(
			"title" => "Receiving Inventory Assistant",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/146.pdf",
			"pay_grade" => "2",
			"salary_min" => "$22,200",
			"salary_mid" => "$28,800",
			"salary_max" => "$35,400",
		),
		array(
			"title" => "Receiving Inventory Assistant Lead",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/147.pdf",
			"pay_grade" => "2",
			"salary_min" => "$22,200",
			"salary_mid" => "$28,800",
			"salary_max" => "$35,400",
		),
		array(
			"title" => "Records Assistant III",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/148.pdf",
			"pay_grade" => "3",
			"salary_min" => "$25,600",
			"salary_mid" => "$33,300",
			"salary_max" => "$41,000",
		),
		array(
			"title" => "Records Officer Master",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/188.pdf",
			"pay_grade" => "4",
			"salary_min" => "$29,000",
			"salary_mid" => "$38,400",
			"salary_max" => "$47,300",
		),
		array(
			"title" => "Research Assistant I",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/149.pdf",
			"pay_grade" => "5",
			"salary_min" => "$34,200",
			"salary_mid" => "$44,400",
			"salary_max" => "$54,600",
		),
		array(
			"title" => "Research Assistant II",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/150.pdf",
			"pay_grade" => "6",
			"salary_min" => "$39,500",
			"salary_mid" => "$51,400",
			"salary_max" => "$63,300",
		),
		array(
			"title" => "Research Assistant III",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/151.pdf",
			"pay_grade" => "7",
			"salary_min" => "$45,700",
			"salary_mid" => "$59,400",
			"salary_max" => "$73,100",
		),
		array(
			"title" => "Residence Hall Associate",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/152.pdf",
			"pay_grade" => "1",
			"salary_min" => "$19,200",
			"salary_mid" => "$24,900",
			"salary_max" => "$30,600",
		),
		array(
			"title" => "Residence Hall Director",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/153.pdf",
			"pay_grade" => "3",
			"salary_min" => "$25,600",
			"salary_mid" => "$33,300",
			"salary_max" => "$41,000",
		),
		array(
			"title" => "Residence Life Specialist",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/154.pdf",
			"pay_grade" => "5",
			"salary_min" => "$35,568",
			"salary_mid" => "$44,400",
			"salary_max" => "$54,600",
		),
		array(
			"title" => "Shipping and Receiving Assistant",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/155.pdf",
			"pay_grade" => "2",
			"salary_min" => "$22,200",
			"salary_mid" => "$28,800",
			"salary_max" => "$35,400",
		),
		array(
			"title" => "Sponsored Programs Administrator",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/156.pdf",
			"pay_grade" => "5",
			"salary_min" => "$35,568",
			"salary_mid" => "$44,400",
			"salary_max" => "$54,600",
		),
		array(
			"title" => "Sports Information Director",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/157.pdf",
			"pay_grade" => "4",
			"salary_min" => "$29,500",
			"salary_mid" => "$38,400",
			"salary_max" => "$47,300",
		),
		array(
			"title" => "Staff Librarian",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/158.pdf",
			"pay_grade" => "5",
			"salary_min" => "$35,568",
			"salary_mid" => "$44,400",
			"salary_max" => "$54,600",
		),
		array(
			"title" => "Student Program Advisor",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/159.pdf",
			"pay_grade" => "4",
			"salary_min" => "$29,500",
			"salary_mid" => "$38,400",
			"salary_max" => "$47,300",
		),
		array(
			"title" => "Student Records Assistant",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/160.pdf",
			"pay_grade" => "2",
			"salary_min" => "$22,200",
			"salary_mid" => "$28,800",
			"salary_max" => "$35,400",
		),
		array(
			"title" => "Student Recruiter Master",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/190.pdf",
			"pay_grade" => "4",
			"salary_min" => "$29,500",
			"salary_mid" => "$38,400",
			"salary_max" => "$47,300",
		),
		array(
			"title" => "Student Services Specialist",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/161.pdf",
			"pay_grade" => "5",
			"salary_min" => "$35,568",
			"salary_mid" => "$44,400",
			"salary_max" => "$54,600",
		),
		array(
			"title" => "Supervisor Admissions",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/162.pdf",
			"pay_grade" => "5",
			"salary_min" => "$35,568",
			"salary_mid" => "$44,400",
			"salary_max" => "$54,600",
		),
		array(
			"title" => "Supervisor Campus Services",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/163.pdf",
			"pay_grade" => "4",
			"salary_min" => "$29,500",
			"salary_mid" => "$38,400",
			"salary_max" => "$47,300",
		),
		array(
			"title" => "Supervisor Computer Operations",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/164.pdf",
			"pay_grade" => "5",
			"salary_min" => "$35,568",
			"salary_mid" => "$44,400",
			"salary_max" => "$54,600",
		),
		array(
			"title" => "Supervisor Facilities",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/165.pdf",
			"pay_grade" => "4",
			"salary_min" => "$29,500",
			"salary_mid" => "$38,400",
			"salary_max" => "$47,300",
		),
		array(
			"title" => "Supervisor Grounds",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/166.pdf",
			"pay_grade" => "4",
			"salary_min" => "$29,500",
			"salary_mid" => "$38,400",
			"salary_max" => "$47,300",
		),
		array(
			"title" => "Supervisor Housing Assignments",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/167.pdf",
			"pay_grade" => "4",
			"salary_min" => "$29,500",
			"salary_mid" => "$38,400",
			"salary_max" => "$47,300",
		),
		array(
			"title" => "Supervisor Student Accounts",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/168.pdf",
			"pay_grade" => "5",
			"salary_min" => "$35,568",
			"salary_mid" => "$44,400",
			"salary_max" => "$54,600",
		),
		array(
			"title" => "Supervisor Student Records",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/169.pdf",
			"pay_grade" => "5",
			"salary_min" => "$35,568",
			"salary_mid" => "$44,400",
			"salary_max" => "$54,600",
		),
		array(
			"title" => "Systems Programmer",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/170.pdf",
			"pay_grade" => "6",
			"salary_min" => "$39,500",
			"salary_mid" => "$51,400",
			"salary_max" => "$63,300",
		),
		array(
			"title" => "Systems Programmer Lead",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/171.pdf",
			"pay_grade" => "9",
			"salary_min" => "$61,000",
			"salary_mid" => "$79,300",
			"salary_max" => "$97,600",
		),
		array(
			"title" => "Systems Programmer Senior",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/172.pdf",
			"pay_grade" => "6",
			"salary_min" => "$39,500",
			"salary_mid" => "$51,400",
			"salary_max" => "$63,300",
		),
		array(
			"title" => "Technology Specialist",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/173.pdf",
			"pay_grade" => "5",
			"salary_min" => "$35,568",
			"salary_mid" => "$44,400",
			"salary_max" => "$54,600",
		),
		array(
			"title" => "Telecommunications Assistant",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/174.pdf",
			"pay_grade" => "4",
			"salary_min" => "$29,500",
			"salary_mid" => "$38,400",
			"salary_max" => "$47,300",
		),
		array(
			"title" => "Telecommunications Network Specialist II",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/175.pdf",
			"pay_grade" => "7",
			"salary_min" => "$45,700",
			"salary_mid" => "$59,400",
			"salary_max" => "$73,100",
		),
		array(
			"title" => "Theatre Technician",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/176.pdf",
			"pay_grade" => "3",
			"salary_min" => "$25,600",
			"salary_mid" => "$33,300",
			"salary_max" => "$41,000",
		),
		array(
			"title" => "Trades Specialist I",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/177.pdf",
			"pay_grade" => "3",
			"salary_min" => "$25,600",
			"salary_mid" => "$33,300",
			"salary_max" => "$41,000",
		),
		array(
			"title" => "Trades Specialist II",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/178.pdf",
			"pay_grade" => "3",
			"salary_min" => "$25,600",
			"salary_mid" => "$33,300",
			"salary_max" => "$41,000",
		),
		array(
			"title" => "Trades Specialist Lead I",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/179.pdf",
			"pay_grade" => "4",
			"salary_min" => "$29,500",
			"salary_mid" => "$38,400",
			"salary_max" => "$47,300",
		),
		array(
			"title" => "Trades Specialist Lead II",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/180.pdf",
			"pay_grade" => "4",
			"salary_min" => "$29,500",
			"salary_mid" => "$38,400",
			"salary_max" => "$47,300",
		),
		array(
			"title" => "Training and Development Specialist",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/181.pdf",
			"pay_grade" => "4",
			"salary_min" => "$29,500",
			"salary_mid" => "$38,400",
			"salary_max" => "$47,300",
		),
		array(
			"title" => "Upholsterer",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/182.pdf",
			"pay_grade" => "3",
			"salary_min" => "$25,600",
			"salary_mid" => "$33,300",
			"salary_max" => "$41,000",
		),
		array(
			"title" => "Uplink Systems Technician",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/183.pdf",
			"pay_grade" => "3",
			"salary_min" => "$25,600",
			"salary_mid" => "$33,300",
			"salary_max" => "$41,000",
		),
		array(
			"title" => "Video Operations Specialist",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/184.pdf",
			"pay_grade" => "4",
			"salary_min" => "$29,500",
			"salary_mid" => "$38,400",
			"salary_max" => "$47,300",
		),
		array(
			"title" => "Visitor Center Assistant",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/185.pdf",
			"pay_grade" => "1",
			"salary_min" => "$19,200",
			"salary_mid" => "$24,900",
			"salary_max" => "$30,600",
		),
		array(
			"title" => "Word Processing Operator",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/186.pdf",
			"pay_grade" => "1",
			"salary_min" => "$19,200",
			"salary_mid" => "$24,900",
			"salary_max" => "$30,600",
		),
		array(
			"title" => "Work Control Technician",
			"pdf_url" => "http://www.marshall.edu/human-resources/files/187.pdf",
			"pay_grade" => "2",
			"salary_min" => "$22,200",
			"salary_mid" => "$28,800",
			"salary_max" => "$35,400",
		)
	);

	if ( ! is_admin() ) {
		require_once( ABSPATH . 'wp-admin/includes/post.php' );
	}

	foreach ( $positions as $position ) {
		$check_exists = post_exists( $position['title'], '', '', 'mu-position' );

		if ( ! $check_exists ) {
			$args = array(
				'post_title'  => $position['title'],
				'post_type'   => 'mu-position',
				'post_status' => 'publish',
				'meta_input'  => array(
					"position_url_pdf"       => $position['pdf_url'],
					"position_new_pay_grade" => $position['pay_grade'],
					"position_salary_min"    => $position['salary_min'],
					"position_salary_mid"    => $position['salary_mid'],
					"position_salary_max"    => $position['salary_max'],
				)
			);

			wp_insert_post( $args );
		}
	}
}
add_shortcode( 'mu_hrcomp_initial_data', 'mu_hrcomp_initial_data' );
